# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Venaqui < Formula
  desc "CLI tool with TUI for downloading files via Real-Debrid and aria2"
  homepage "https://github.com/mhrsntrk/venaqui"
  version "0.1.0"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/mhrsntrk/venaqui/releases/download/v0.1.0/venaqui_0.1.0_darwin_amd64.tar.gz"
      sha256 "PLACEHOLDER_SHA256"

      def install
        bin.install "venaqui"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/mhrsntrk/venaqui/releases/download/v0.1.0/venaqui_0.1.0_darwin_arm64.tar.gz"
      sha256 "PLACEHOLDER_SHA256"

      def install
        bin.install "venaqui"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      if Hardware::CPU.is_64_bit?
        url "https://github.com/mhrsntrk/venaqui/releases/download/v0.1.0/venaqui_0.1.0_linux_amd64.tar.gz"
        sha256 "PLACEHOLDER_SHA256"

        def install
          bin.install "venaqui"
        end
      end
    end
    if Hardware::CPU.arm?
      if Hardware::CPU.is_64_bit?
        url "https://github.com/mhrsntrk/venaqui/releases/download/v0.1.0/venaqui_0.1.0_linux_arm64.tar.gz"
        sha256 "PLACEHOLDER_SHA256"

        def install
          bin.install "venaqui"
        end
      end
    end
  end

  depends_on "aria2"

  test do
    system "#{bin}/venaqui", "--version"
  end
end
